import '../../../core/shortcuts/default_shortcuts.dart';
import '../../../l10n/app_localizations.dart';

/// 快捷键动作与上下文的本地化文案，设置面板与帮助弹窗共用同一份解析。

/// actionKey 无对应译文时退回裸键名，保持旧行为
String shortcutActionDisplayName(AppLocalizations l10n, String actionKey) {
  switch (actionKey) {
    case 'shortcut_action_navigate_to_generation':
      return l10n.shortcut_action_navigate_to_generation;
    case 'shortcut_action_navigate_to_local_gallery':
      return l10n.shortcut_action_navigate_to_local_gallery;
    case 'shortcut_action_navigate_to_online_gallery':
      return l10n.shortcut_action_navigate_to_online_gallery;
    case 'shortcut_action_navigate_to_random_config':
      return l10n.shortcut_action_navigate_to_random_config;
    case 'shortcut_action_navigate_to_tag_library':
      return l10n.shortcut_action_navigate_to_tag_library;
    case 'shortcut_action_navigate_to_statistics':
      return l10n.shortcut_action_navigate_to_statistics;
    case 'shortcut_action_navigate_to_settings':
      return l10n.shortcut_action_navigate_to_settings;
    case 'shortcut_action_navigate_to_vibe_library':
      return l10n.shortcut_action_navigate_to_vibe_library;
    case 'shortcut_action_generate_image':
      return l10n.shortcut_action_generate_image;
    case 'shortcut_action_generation_prev_image':
      return l10n.shortcut_action_generation_prev_image;
    case 'shortcut_action_generation_next_image':
      return l10n.shortcut_action_generation_next_image;
    case 'shortcut_action_cancel_generation':
      return l10n.shortcut_action_cancel_generation;
    case 'shortcut_action_add_to_queue':
      return l10n.shortcut_action_add_to_queue;
    case 'shortcut_action_random_prompt':
      return l10n.shortcut_action_random_prompt;
    case 'shortcut_action_clear_prompt':
      return l10n.shortcut_action_clear_prompt;
    case 'shortcut_action_toggle_prompt_mode':
      return l10n.shortcut_action_toggle_prompt_mode;
    case 'shortcut_action_open_tag_library':
      return l10n.shortcut_action_open_tag_library;
    case 'shortcut_action_save_image':
      return l10n.shortcut_action_save_image;
    case 'shortcut_action_upscale_image':
      return l10n.shortcut_action_upscale_image;
    case 'shortcut_action_copy_image':
      return l10n.shortcut_action_copy_image;
    case 'shortcut_action_fullscreen_preview':
      return l10n.shortcut_action_fullscreen_preview;
    case 'shortcut_action_open_params_panel':
      return l10n.shortcut_action_open_params_panel;
    case 'shortcut_action_open_history_panel':
      return l10n.shortcut_action_open_history_panel;
    case 'shortcut_action_reuse_params':
      return l10n.shortcut_action_reuse_params;
    case 'shortcut_action_previous_image':
      return l10n.shortcut_action_previous_image;
    case 'shortcut_action_next_image':
      return l10n.shortcut_action_next_image;
    case 'shortcut_action_zoom_in':
      return l10n.shortcut_action_zoom_in;
    case 'shortcut_action_zoom_out':
      return l10n.shortcut_action_zoom_out;
    case 'shortcut_action_reset_zoom':
      return l10n.shortcut_action_reset_zoom;
    case 'shortcut_action_toggle_fullscreen':
      return l10n.shortcut_action_toggle_fullscreen;
    case 'shortcut_action_close_viewer':
      return l10n.shortcut_action_close_viewer;
    case 'shortcut_action_toggle_favorite':
      return l10n.shortcut_action_toggle_favorite;
    case 'shortcut_action_copy_prompt':
      return l10n.shortcut_action_copy_prompt;
    case 'shortcut_action_reuse_gallery_params':
      return l10n.shortcut_action_reuse_gallery_params;
    case 'shortcut_action_delete_image':
      return l10n.shortcut_action_delete_image;
    case 'shortcut_action_previous_page':
      return l10n.shortcut_action_previous_page;
    case 'shortcut_action_next_page':
      return l10n.shortcut_action_next_page;
    case 'shortcut_action_refresh_gallery':
      return l10n.shortcut_action_refresh_gallery;
    case 'shortcut_action_focus_search':
      return l10n.shortcut_action_focus_search;
    case 'shortcut_action_enter_selection_mode':
      return l10n.shortcut_action_enter_selection_mode;
    case 'shortcut_action_open_filter_panel':
      return l10n.shortcut_action_open_filter_panel;
    case 'shortcut_action_clear_filter':
      return l10n.shortcut_action_clear_filter;
    case 'shortcut_action_toggle_category_panel':
      return l10n.shortcut_action_toggle_category_panel;
    case 'shortcut_action_jump_to_date':
      return l10n.shortcut_action_jump_to_date;
    case 'shortcut_action_open_folder':
      return l10n.shortcut_action_open_folder;
    case 'shortcut_action_select_all_tags':
      return l10n.shortcut_action_select_all_tags;
    case 'shortcut_action_deselect_all_tags':
      return l10n.shortcut_action_deselect_all_tags;
    case 'shortcut_action_new_category':
      return l10n.shortcut_action_new_category;
    case 'shortcut_action_new_tag':
      return l10n.shortcut_action_new_tag;
    case 'shortcut_action_search_tags':
      return l10n.shortcut_action_search_tags;
    case 'shortcut_action_batch_delete_tags':
      return l10n.shortcut_action_batch_delete_tags;
    case 'shortcut_action_batch_copy_tags':
      return l10n.shortcut_action_batch_copy_tags;
    case 'shortcut_action_send_to_home':
      return l10n.shortcut_action_send_to_home;
    case 'shortcut_action_exit_selection_mode':
      return l10n.shortcut_action_exit_selection_mode;
    case 'shortcut_action_sync_danbooru':
      return l10n.shortcut_action_sync_danbooru;
    case 'shortcut_action_generate_preview':
      return l10n.shortcut_action_generate_preview;
    case 'shortcut_action_search_presets':
      return l10n.shortcut_action_search_presets;
    case 'shortcut_action_new_preset':
      return l10n.shortcut_action_new_preset;
    case 'shortcut_action_duplicate_preset':
      return l10n.shortcut_action_duplicate_preset;
    case 'shortcut_action_delete_preset':
      return l10n.shortcut_action_delete_preset;
    case 'shortcut_action_close_config':
      return l10n.shortcut_action_close_config;
    case 'shortcut_action_minimize_to_tray':
      return l10n.shortcut_action_minimize_to_tray;
    case 'shortcut_action_quit_app':
      return l10n.shortcut_action_quit_app;
    case 'shortcut_action_show_shortcut_help':
      return l10n.shortcut_action_show_shortcut_help;
    case 'shortcut_action_toggle_queue':
      return l10n.shortcut_action_toggle_queue;
    case 'shortcut_action_toggle_queue_pause':
      return l10n.shortcut_action_toggle_queue_pause;
    case 'shortcut_action_toggle_theme':
      return l10n.shortcut_action_toggle_theme;
    case 'shortcut_action_vibe_import':
      return l10n.shortcut_action_vibe_import;
    case 'shortcut_action_vibe_export':
      return l10n.shortcut_action_vibe_export;
    case 'shortcut_action_vibe_detail_send_to_generation':
      return l10n.shortcut_action_vibe_detail_send_to_generation;
    case 'shortcut_action_vibe_detail_export':
      return l10n.shortcut_action_vibe_detail_export;
    case 'shortcut_action_vibe_detail_rename':
      return l10n.shortcut_action_vibe_detail_rename;
    case 'shortcut_action_vibe_detail_delete':
      return l10n.shortcut_action_vibe_detail_delete;
    case 'shortcut_action_vibe_detail_toggle_favorite':
      return l10n.shortcut_action_vibe_detail_toggle_favorite;
    case 'shortcut_action_vibe_detail_prev_sub_vibe':
      return l10n.shortcut_action_vibe_detail_prev_sub_vibe;
    case 'shortcut_action_vibe_detail_next_sub_vibe':
      return l10n.shortcut_action_vibe_detail_next_sub_vibe;
    default:
      return shortcutActionFallbackName(actionKey);
  }
}

String shortcutActionFallbackName(String actionKey) =>
    actionKey.replaceAll('shortcut_action_', '');

String shortcutContextDisplayName(
  AppLocalizations l10n,
  ShortcutContext shortcutContext,
) {
  switch (shortcutContext) {
    case ShortcutContext.global:
      return l10n.shortcut_context_global;
    case ShortcutContext.generation:
      return l10n.shortcut_context_generation;
    case ShortcutContext.gallery:
      return l10n.shortcut_context_gallery;
    case ShortcutContext.viewer:
      return l10n.shortcut_context_viewer;
    case ShortcutContext.tagLibrary:
      return l10n.shortcut_context_tag_library;
    case ShortcutContext.randomConfig:
      return l10n.shortcut_context_random_config;
    case ShortcutContext.settings:
      return l10n.shortcut_context_settings;
    case ShortcutContext.input:
      return l10n.shortcut_context_input;
    case ShortcutContext.vibeDetail:
      return l10n.shortcut_context_vibe_detail;
  }
}
