// GENERATED from @earendil-works/pi-ai 1.0.0.
// Source: dist/providers/data/*.json. Do not edit by hand.

const piModelDisplayNames = <String, Map<String, String>>{
  'openai': {
    'gpt-4': 'GPT-4',
    'gpt-4-turbo': 'GPT-4 Turbo',
    'gpt-4.1': 'GPT-4.1',
    'gpt-4.1-mini': 'GPT-4.1 mini',
    'gpt-4.1-nano': 'GPT-4.1 nano',
    'gpt-4o': 'GPT-4o',
    'gpt-4o-2024-05-13': 'GPT-4o (2024-05-13)',
    'gpt-4o-2024-08-06': 'GPT-4o (2024-08-06)',
    'gpt-4o-2024-11-20': 'GPT-4o (2024-11-20)',
    'gpt-4o-mini': 'GPT-4o mini',
    'gpt-5': 'GPT-5',
    'gpt-5-chat-latest': 'GPT-5 Chat Latest',
    'gpt-5-mini': 'GPT-5 Mini',
    'gpt-5-nano': 'GPT-5 Nano',
    'gpt-5-pro': 'GPT-5 Pro',
    'gpt-5.1': 'GPT-5.1',
    'gpt-5.2': 'GPT-5.2',
    'gpt-5.2-chat-latest': 'GPT-5.2 Chat',
    'gpt-5.2-pro': 'GPT-5.2 Pro',
    'gpt-5.3-chat-latest': 'GPT-5.3 Chat (latest)',
    'gpt-5.3-codex': 'GPT-5.3 Codex',
    'gpt-5.3-codex-spark': 'GPT-5.3 Codex Spark',
    'gpt-5.4': 'GPT-5.4',
    'gpt-5.4-mini': 'GPT-5.4 mini',
    'gpt-5.4-nano': 'GPT-5.4 nano',
    'gpt-5.4-pro': 'GPT-5.4 Pro',
    'gpt-5.5': 'GPT-5.5',
    'gpt-5.5-pro': 'GPT-5.5 Pro',
    'gpt-5.6-luna': 'GPT-5.6 Luna',
    'gpt-5.6-sol': 'GPT-5.6 Sol',
    'gpt-5.6-terra': 'GPT-5.6 Terra',
    'gpt-6-astra': 'GPT-6 Astra',
    'gpt-6-luna': 'GPT-6 Luna',
    'gpt-6-sol': 'GPT-6 Sol',
    'gpt-6.1-sol': 'GPT-6.1 Sol',
    'gpt-daybreak-blue-latest': 'Daybreak Blue',
    'gpt-daybreak-red-latest': 'Daybreak Red',
    'gpt-realtime-2.1': 'GPT-Realtime-2.1',
    'o1': 'o1',
    'o1-pro': 'o1-pro',
    'o3': 'o3',
    'o3-mini': 'o3-mini',
    'o3-pro': 'o3-pro',
    'o4-mini': 'o4-mini',
  },
  'anthropic': {
    'claude-fable-5': 'Claude Fable 5',
    'claude-fable-5-1': 'Claude Fable 5.1',
    'claude-haiku-4-5': 'Claude Haiku 4.5 (latest)',
    'claude-haiku-4-5-20251001': 'Claude Haiku 4.5',
    'claude-opus-4-5': 'Claude Opus 4.5 (latest)',
    'claude-opus-4-5-20251101': 'Claude Opus 4.5',
    'claude-opus-4-6': 'Claude Opus 4.6',
    'claude-opus-4-7': 'Claude Opus 4.7',
    'claude-opus-4-8': 'Claude Opus 4.8',
    'claude-opus-5': 'Claude Opus 5',
    'claude-opus-5-5': 'Claude Opus 5.5',
    'claude-sonnet-4-5': 'Claude Sonnet 4.5 (latest)',
    'claude-sonnet-4-5-20250929': 'Claude Sonnet 4.5',
    'claude-sonnet-4-6': 'Claude Sonnet 4.6',
    'claude-sonnet-5': 'Claude Sonnet 5',
    'claude-sonnet-5-5': 'Claude Sonnet 5.5',
  },
  'google': {
    'deep-research-max-preview-04-2026':
        'Deep Research Max Preview (Apr-21-2026)',
    'deep-research-preview-04-2026': 'Deep Research Preview (Apr-21-2026)',
    'gemini-2.5-computer-use-preview-10-2025':
        'Gemini 2.5 Computer Use Preview 10-2025',
    'gemini-2.5-flash': 'Gemini 2.5 Flash',
    'gemini-2.5-flash-lite': 'Gemini 2.5 Flash-Lite',
    'gemini-2.5-pro': 'Gemini 2.5 Pro',
    'gemini-3-flash-preview': 'Gemini 3 Flash Preview',
    'gemini-3.1-flash-lite': 'Gemini 3.1 Flash Lite',
    'gemini-3.1-flash-lite-image': 'Nano Banana 2 Lite',
    'gemini-3.1-flash-lite-preview': 'Gemini 3.1 Flash Lite Preview',
    'gemini-3.1-flash-live-preview': 'Gemini 3.1 Flash Live Preview',
    'gemini-3.1-pro-preview': 'Gemini 3.1 Pro Preview',
    'gemini-3.1-pro-preview-customtools': 'Gemini 3.1 Pro Preview Custom Tools',
    'gemini-3.5-flash': 'Gemini 3.5 Flash',
    'gemini-3.5-flash-lite': 'Gemini 3.5 Flash Lite',
    'gemini-3.6-flash': 'Gemini 3.6 Flash',
    'gemini-3.7-flash': 'Gemini 3.7 Flash',
    'gemini-3.8-flash': 'Gemini 3.8 Flash',
    'gemini-flash-latest': 'Gemini Flash Latest',
    'gemini-flash-lite-latest': 'Gemini Flash-Lite Latest',
    'gemma-4-26b-a4b-it': 'Gemma 4 26B A4B IT',
    'gemma-4-31b-it': 'Gemma 4 31B IT',
  },
  'deepseek': {
    'deepseek-flash': 'DeepSeek V4.1 Flash',
    'deepseek-v4-pro': 'DeepSeek V4 Pro',
  },
  'openrouter': {
    'aion-labs/aion-2.0': 'AionLabs: Aion-2.0',
    'aion-labs/aion-3.0': 'AionLabs: Aion-3.0',
    'aion-labs/aion-3.0-mini': 'AionLabs: Aion-3.0-Mini',
    'aion-labs/aion-3.5': 'AionLabs: Aion 3.5',
    'aion-labs/aion-3.5-mini': 'AionLabs: Aion 3.5 Mini',
    'amazon/nova-2-lite-v1': 'Amazon: Nova 2 Lite',
    'amazon/nova-lite-v1': 'Amazon: Nova Lite 1.0',
    'amazon/nova-micro-v1': 'Amazon: Nova Micro 1.0',
    'amazon/nova-premier-v1': 'Amazon: Nova Premier 1.0',
    'amazon/nova-pro-v1': 'Amazon: Nova Pro 1.0',
    'anthropic/claude-fable-5': 'Anthropic: Claude Fable 5',
    'anthropic/claude-fable-5.1': 'Anthropic: Claude Fable 5.1',
    'anthropic/claude-fable-5.1:batch': 'Anthropic: Claude Fable 5.1 (batch)',
    'anthropic/claude-fable-5:batch': 'Anthropic: Claude Fable 5 (batch)',
    'anthropic/claude-haiku-4.5': 'Anthropic: Claude Haiku 4.5',
    'anthropic/claude-haiku-4.5:batch': 'Anthropic: Claude Haiku 4.5 (batch)',
    'anthropic/claude-opus-4.1': 'Anthropic: Claude Opus 4.1',
    'anthropic/claude-opus-4.1:batch': 'Anthropic: Claude Opus 4.1 (batch)',
    'anthropic/claude-opus-4.5': 'Anthropic: Claude Opus 4.5',
    'anthropic/claude-opus-4.5:batch': 'Anthropic: Claude Opus 4.5 (batch)',
    'anthropic/claude-opus-4.6': 'Anthropic: Claude Opus 4.6',
    'anthropic/claude-opus-4.6:batch': 'Anthropic: Claude Opus 4.6 (batch)',
    'anthropic/claude-opus-4.7': 'Anthropic: Claude Opus 4.7',
    'anthropic/claude-opus-4.7:batch': 'Anthropic: Claude Opus 4.7 (batch)',
    'anthropic/claude-opus-4.8': 'Anthropic: Claude Opus 4.8',
    'anthropic/claude-opus-4.8:batch': 'Anthropic: Claude Opus 4.8 (batch)',
    'anthropic/claude-opus-5': 'Anthropic: Claude Opus 5',
    'anthropic/claude-opus-5.5': 'Anthropic: Claude Opus 5.5',
    'anthropic/claude-opus-5.5:batch': 'Anthropic: Claude Opus 5.5 (batch)',
    'anthropic/claude-opus-5:batch': 'Anthropic: Claude Opus 5 (batch)',
    'anthropic/claude-sonnet-4': 'Anthropic: Claude Sonnet 4',
    'anthropic/claude-sonnet-4.5': 'Anthropic: Claude Sonnet 4.5',
    'anthropic/claude-sonnet-4.5:batch': 'Anthropic: Claude Sonnet 4.5 (batch)',
    'anthropic/claude-sonnet-4.6': 'Anthropic: Claude Sonnet 4.6',
    'anthropic/claude-sonnet-4.6:batch': 'Anthropic: Claude Sonnet 4.6 (batch)',
    'anthropic/claude-sonnet-5': 'Anthropic: Claude Sonnet 5',
    'anthropic/claude-sonnet-5.5': 'Anthropic: Claude Sonnet 5.5',
    'anthropic/claude-sonnet-5.5:batch': 'Anthropic: Claude Sonnet 5.5 (batch)',
    'anthropic/claude-sonnet-5:batch': 'Anthropic: Claude Sonnet 5 (batch)',
    'apodex/apodex-1.1-mini:free': 'Apodex: Apodex 1.1 Mini (free)',
    'arcee-ai/trinity-large-thinking': 'Arcee AI: Trinity Large Thinking',
    'auto': 'Auto',
    'bytedance-seed/seed-1.6': 'ByteDance Seed: Seed 1.6',
    'bytedance-seed/seed-1.6-flash': 'ByteDance Seed: Seed 1.6 Flash',
    'bytedance-seed/seed-2-1-turbo': 'ByteDance Seed: Seed 2.1 Turbo',
    'bytedance-seed/seed-2.0-code': 'ByteDance Seed: Seed-2.0-Code',
    'bytedance-seed/seed-2.0-lite': 'ByteDance Seed: Seed-2.0-Lite',
    'bytedance-seed/seed-2.0-mini': 'ByteDance Seed: Seed-2.0-Mini',
    'cohere/command-a-plus': 'Cohere: Command A+',
    'cohere/command-r-08-2024': 'Cohere: Command R (08-2024)',
    'cohere/command-r-plus-08-2024': 'Cohere: Command R+ (08-2024)',
    'cohere/north-mini-code:free': 'Cohere: North Mini Code (free)',
    'deepseek/deepseek-chat': 'DeepSeek: DeepSeek V3',
    'deepseek/deepseek-chat-v3-0324': 'DeepSeek: DeepSeek V3 0324',
    'deepseek/deepseek-chat-v3.1': 'DeepSeek: DeepSeek V3.1',
    'deepseek/deepseek-r1': 'DeepSeek: R1',
    'deepseek/deepseek-r1-0528': 'DeepSeek: R1 0528',
    'deepseek/deepseek-v3.1-terminus': 'DeepSeek: DeepSeek V3.1 Terminus',
    'deepseek/deepseek-v3.2': 'DeepSeek: DeepSeek V3.2',
    'deepseek/deepseek-v3.2-exp': 'DeepSeek: DeepSeek V3.2 Exp',
    'deepseek/deepseek-v4-flash': 'DeepSeek: DeepSeek V4 Flash 0423',
    'deepseek/deepseek-v4-flash-0731': 'DeepSeek: DeepSeek V4 Flash 0731',
    'deepseek/deepseek-v4-flash-vision-exp':
        'DeepSeek: DeepSeek V4 Flash Vision Exp',
    'deepseek/deepseek-v4-pro': 'DeepSeek: DeepSeek V4 Pro 0423',
    'deepseek/deepseek-v4-pro-0813': 'DeepSeek: DeepSeek V4 Pro 0813',
    'deepseek/deepseek-v4.1-flash': 'DeepSeek: DeepSeek V4.1 Flash',
    'deepseek/deepseek-v4.1-flash:batch':
        'DeepSeek: DeepSeek V4.1 Flash (batch)',
    'dots-studio/dots-3-note-preview:free':
        'Dots Studio: Dots3-Note Preview (free)',
    'fireworks/ember-1': 'Fireworks: Ember-1',
    'google/gemini-2.5-flash': 'Google: Gemini 2.5 Flash',
    'google/gemini-2.5-flash-lite': 'Google: Gemini 2.5 Flash Lite',
    'google/gemini-2.5-flash-lite:batch':
        'Google: Gemini 2.5 Flash Lite (batch)',
    'google/gemini-2.5-flash:batch': 'Google: Gemini 2.5 Flash (batch)',
    'google/gemini-2.5-pro': 'Google: Gemini 2.5 Pro',
    'google/gemini-2.5-pro-preview': 'Google: Gemini 2.5 Pro Preview 06-05',
    'google/gemini-2.5-pro:batch': 'Google: Gemini 2.5 Pro (batch)',
    'google/gemini-3-flash-preview': 'Google: Gemini 3 Flash Preview',
    'google/gemini-3-flash-preview:batch':
        'Google: Gemini 3 Flash Preview (batch)',
    'google/gemini-3-pro-image': 'Google: Nano Banana Pro (Gemini 3 Pro Image)',
    'google/gemini-3.1-flash-lite': 'Google: Gemini 3.1 Flash Lite',
    'google/gemini-3.1-flash-lite-preview':
        'Google: Gemini 3.1 Flash Lite Preview',
    'google/gemini-3.1-flash-lite:batch':
        'Google: Gemini 3.1 Flash Lite (batch)',
    'google/gemini-3.1-pro-preview': 'Google: Gemini 3.1 Pro Preview',
    'google/gemini-3.1-pro-preview-customtools':
        'Google: Gemini 3.1 Pro Preview Custom Tools',
    'google/gemini-3.1-pro-preview:batch':
        'Google: Gemini 3.1 Pro Preview (batch)',
    'google/gemini-3.5-flash': 'Google: Gemini 3.5 Flash',
    'google/gemini-3.5-flash-lite': 'Google: Gemini 3.5 Flash Lite',
    'google/gemini-3.5-flash-lite:batch':
        'Google: Gemini 3.5 Flash Lite (batch)',
    'google/gemini-3.5-flash:batch': 'Google: Gemini 3.5 Flash (batch)',
    'google/gemini-3.6-flash': 'Google: Gemini 3.6 Flash',
    'google/gemini-3.6-flash:batch': 'Google: Gemini 3.6 Flash (batch)',
    'google/gemini-3.7-flash': 'Google: Gemini 3.7 Flash',
    'google/gemini-3.7-flash:batch': 'Google: Gemini 3.7 Flash (batch)',
    'google/gemini-3.8-flash': 'Google: Gemini 3.8 Flash',
    'google/gemini-3.8-flash:batch': 'Google: Gemini 3.8 Flash (batch)',
    'google/gemma-3-12b-it': 'Google: Gemma 3 12B',
    'google/gemma-3-27b-it': 'Google: Gemma 3 27B',
    'google/gemma-4-26b-a4b-it': 'Google: Gemma 4 26B A4B',
    'google/gemma-4-26b-a4b-it:free': 'Google: Gemma 4 26B A4B  (free)',
    'google/gemma-4-31b-it': 'Google: Gemma 4 31B',
    'google/gemma-4-31b-it:free': 'Google: Gemma 4 31B (free)',
    'ibm-granite/granite-4.2-8b': 'IBM: Granite 4.2 8B',
    'inception/mercury-2': 'Inception: Mercury 2',
    'inception/mercury-2.5': 'Inception: Mercury 2.5',
    'inclusionai/ling-3.0-flash': 'inclusionAI: Ling 3.0 Flash',
    'inclusionai/ling-3.0-flash-fin': 'inclusionAI: Ling 3.0 Flash Fin',
    'inclusionai/ling-3.0-flash-sante:free':
        'inclusionAI: Ling 3.0 Flash Sante (free)',
    'inclusionai/ling-3.0-flash-vl': 'inclusionAI: Ling 3.0 Flash VL',
    'kwaipilot/kat-coder-pro-v2.5': 'Kwaipilot: KAT-Coder-Pro V2.5',
    'liquid/lfm-2.5-2.6b:free': 'LiquidAI: LFM2.5-2.6B (free)',
    'meituan/longcat-2.0': 'Meituan: LongCat 2.0',
    'meta-llama/llama-3.1-70b-instruct': 'Meta: Llama 3.1 70B Instruct',
    'meta-llama/llama-3.1-8b-instruct': 'Meta: Llama 3.1 8B Instruct',
    'meta-llama/llama-3.3-70b-instruct': 'Meta: Llama 3.3 70B Instruct',
    'meta-llama/llama-4-maverick': 'Meta: Llama 4 Maverick',
    'meta-llama/llama-4-scout': 'Meta: Llama 4 Scout',
    'meta/muse-glimmer-30b': 'Meta: Muse Glimmer 30B',
    'meta/muse-spark-1.1': 'Meta: Muse Spark 1.1',
    'meta/muse-spark-1.2': 'Meta: Muse Spark 1.2',
    'meta/muse-spark-1.2-contributor': 'Meta: Muse Spark 1.2 Contributor',
    'meta/muse-spark-1.3': 'Meta: Muse Spark 1.3',
    'meta/muse-spark-1.3-contributor': 'Meta: Muse Spark 1.3 Contributor',
    'minimax/minimax-m1': 'MiniMax: MiniMax M1',
    'minimax/minimax-m2': 'MiniMax: MiniMax M2',
    'minimax/minimax-m2.1': 'MiniMax: MiniMax M2.1',
    'minimax/minimax-m2.5': 'MiniMax: MiniMax M2.5',
    'minimax/minimax-m2.7': 'MiniMax: MiniMax M2.7',
    'minimax/minimax-m3': 'MiniMax: MiniMax M3',
    'mistralai/codestral-2508': 'Mistral: Codestral 2508',
    'mistralai/codestral-2508:batch': 'Mistral: Codestral 2508 (batch)',
    'mistralai/devstral-2512': 'Mistral: Devstral 2 2512',
    'mistralai/ministral-14b-2512': 'Mistral: Ministral 3 14B 2512',
    'mistralai/ministral-3b-2512': 'Mistral: Ministral 3 3B 2512',
    'mistralai/ministral-8b-2512': 'Mistral: Ministral 3 8B 2512',
    'mistralai/ministral-8b-2512:batch': 'Mistral: Ministral 3 8B 2512 (batch)',
    'mistralai/mistral-large': 'Mistral Large',
    'mistralai/mistral-large-2407': 'Mistral Large 2407',
    'mistralai/mistral-large-2512': 'Mistral: Mistral Large 3 2512',
    'mistralai/mistral-large-2512:batch':
        'Mistral: Mistral Large 3 2512 (batch)',
    'mistralai/mistral-medium-3': 'Mistral: Mistral Medium 3',
    'mistralai/mistral-medium-3-5': 'Mistral: Mistral Medium 3.5',
    'mistralai/mistral-medium-3-5:batch': 'Mistral: Mistral Medium 3.5 (batch)',
    'mistralai/mistral-medium-3.1': 'Mistral: Mistral Medium 3.1',
    'mistralai/mistral-medium-3.1:batch': 'Mistral: Mistral Medium 3.1 (batch)',
    'mistralai/mistral-nemo': 'Mistral: Mistral Nemo',
    'mistralai/mistral-saba': 'Mistral: Saba',
    'mistralai/mistral-small-2603': 'Mistral: Mistral Small 4',
    'mistralai/mistral-small-2603:batch': 'Mistral: Mistral Small 4 (batch)',
    'mistralai/mistral-small-3.1-24b-instruct':
        'Mistral: Mistral Small 3.1 24B',
    'mistralai/mistral-small-3.2-24b-instruct':
        'Mistral: Mistral Small 3.2 24B',
    'mistralai/mixtral-8x22b-instruct': 'Mistral: Mixtral 8x22B Instruct',
    'mistralai/voxtral-small-24b-2507': 'Mistral: Voxtral Small 24B 2507',
    'moonshotai/kimi-k2': 'MoonshotAI: Kimi K2 0711',
    'moonshotai/kimi-k2-0905': 'MoonshotAI: Kimi K2 0905',
    'moonshotai/kimi-k2-thinking': 'MoonshotAI: Kimi K2 Thinking',
    'moonshotai/kimi-k2.5': 'MoonshotAI: Kimi K2.5',
    'moonshotai/kimi-k2.6': 'MoonshotAI: Kimi K2.6',
    'moonshotai/kimi-k2.7-code': 'MoonshotAI: Kimi K2.7 Code',
    'moonshotai/kimi-k3': 'MoonshotAI: Kimi K3',
    'moonshotai/kimi-k3:batch': 'MoonshotAI: Kimi K3 (batch)',
    'nex-agi/nex-n2.5-pro': 'Nex AGI: Nex-N2.5-Pro',
    'nvidia/nemotron-3-nano-30b-a3b': 'NVIDIA: Nemotron 3 Nano 30B A3B',
    'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free':
        'NVIDIA: Nemotron 3 Nano Omni (free)',
    'nvidia/nemotron-3-super-120b-a12b': 'NVIDIA: Nemotron 3 Super',
    'nvidia/nemotron-3-super-120b-a12b:free': 'NVIDIA: Nemotron 3 Super (free)',
    'nvidia/nemotron-3-ultra-550b-a55b': 'NVIDIA: Nemotron 3 Ultra',
    'nvidia/nemotron-3-ultra-550b-a55b:free': 'NVIDIA: Nemotron 3 Ultra (free)',
    'nvidia/nemotron-3.5-lightning': 'NVIDIA: Nemotron 3.5 Lightning',
    'nvidia/nemotron-3.5-lightning:free':
        'NVIDIA: Nemotron 3.5 Lightning (free)',
    'openai/gpt-3.5-turbo': 'OpenAI: GPT-3.5 Turbo',
    'openai/gpt-3.5-turbo-0613': 'OpenAI: GPT-3.5 Turbo (older v0613)',
    'openai/gpt-3.5-turbo-16k': 'OpenAI: GPT-3.5 Turbo 16k',
    'openai/gpt-3.5-turbo:batch': 'OpenAI: GPT-3.5 Turbo (batch)',
    'openai/gpt-4': 'OpenAI: GPT-4',
    'openai/gpt-4-turbo': 'OpenAI: GPT-4 Turbo',
    'openai/gpt-4-turbo:batch': 'OpenAI: GPT-4 Turbo (batch)',
    'openai/gpt-4.1': 'OpenAI: GPT-4.1',
    'openai/gpt-4.1-mini': 'OpenAI: GPT-4.1 Mini',
    'openai/gpt-4.1-mini:batch': 'OpenAI: GPT-4.1 Mini (batch)',
    'openai/gpt-4.1-nano': 'OpenAI: GPT-4.1 Nano',
    'openai/gpt-4.1-nano:batch': 'OpenAI: GPT-4.1 Nano (batch)',
    'openai/gpt-4.1:batch': 'OpenAI: GPT-4.1 (batch)',
    'openai/gpt-4o': 'OpenAI: GPT-4o',
    'openai/gpt-4o-2024-05-13': 'OpenAI: GPT-4o (2024-05-13)',
    'openai/gpt-4o-2024-08-06': 'OpenAI: GPT-4o (2024-08-06)',
    'openai/gpt-4o-2024-11-20': 'OpenAI: GPT-4o (2024-11-20)',
    'openai/gpt-4o-mini': 'OpenAI: GPT-4o-mini',
    'openai/gpt-4o-mini-2024-07-18': 'OpenAI: GPT-4o-mini (2024-07-18)',
    'openai/gpt-4o-mini:batch': 'OpenAI: GPT-4o-mini (batch)',
    'openai/gpt-4o:batch': 'OpenAI: GPT-4o (batch)',
    'openai/gpt-5': 'OpenAI: GPT-5',
    'openai/gpt-5-mini': 'OpenAI: GPT-5 Mini',
    'openai/gpt-5-mini:batch': 'OpenAI: GPT-5 Mini (batch)',
    'openai/gpt-5-nano': 'OpenAI: GPT-5 Nano',
    'openai/gpt-5-nano:batch': 'OpenAI: GPT-5 Nano (batch)',
    'openai/gpt-5-pro': 'OpenAI: GPT-5 Pro',
    'openai/gpt-5-pro:batch': 'OpenAI: GPT-5 Pro (batch)',
    'openai/gpt-5.1': 'OpenAI: GPT-5.1',
    'openai/gpt-5.1-codex': 'OpenAI: GPT-5.1-Codex',
    'openai/gpt-5.1-codex-max': 'OpenAI: GPT-5.1-Codex-Max',
    'openai/gpt-5.1-codex-mini': 'OpenAI: GPT-5.1-Codex-Mini',
    'openai/gpt-5.1:batch': 'OpenAI: GPT-5.1 (batch)',
    'openai/gpt-5.2': 'OpenAI: GPT-5.2',
    'openai/gpt-5.2-chat': 'OpenAI: GPT-5.2 Chat',
    'openai/gpt-5.2-codex': 'OpenAI: GPT-5.2-Codex',
    'openai/gpt-5.2-pro': 'OpenAI: GPT-5.2 Pro',
    'openai/gpt-5.2-pro:batch': 'OpenAI: GPT-5.2 Pro (batch)',
    'openai/gpt-5.2:batch': 'OpenAI: GPT-5.2 (batch)',
    'openai/gpt-5.3-codex': 'OpenAI: GPT-5.3-Codex',
    'openai/gpt-5.4': 'OpenAI: GPT-5.4',
    'openai/gpt-5.4-mini': 'OpenAI: GPT-5.4 Mini',
    'openai/gpt-5.4-mini:batch': 'OpenAI: GPT-5.4 Mini (batch)',
    'openai/gpt-5.4-nano': 'OpenAI: GPT-5.4 Nano',
    'openai/gpt-5.4-nano:batch': 'OpenAI: GPT-5.4 Nano (batch)',
    'openai/gpt-5.4-pro': 'OpenAI: GPT-5.4 Pro',
    'openai/gpt-5.4-pro:batch': 'OpenAI: GPT-5.4 Pro (batch)',
    'openai/gpt-5.4:batch': 'OpenAI: GPT-5.4 (batch)',
    'openai/gpt-5.5': 'OpenAI: GPT-5.5',
    'openai/gpt-5.5-pro': 'OpenAI: GPT-5.5 Pro',
    'openai/gpt-5.5-pro:batch': 'OpenAI: GPT-5.5 Pro (batch)',
    'openai/gpt-5.5:batch': 'OpenAI: GPT-5.5 (batch)',
    'openai/gpt-5.6-luna': 'OpenAI: GPT-5.6 Luna',
    'openai/gpt-5.6-luna-pro': 'OpenAI: GPT-5.6 Luna Pro',
    'openai/gpt-5.6-luna-pro:batch': 'OpenAI: GPT-5.6 Luna Pro (batch)',
    'openai/gpt-5.6-luna:batch': 'OpenAI: GPT-5.6 Luna (batch)',
    'openai/gpt-5.6-sol': 'OpenAI: GPT-5.6 Sol',
    'openai/gpt-5.6-sol-pro': 'OpenAI: GPT-5.6 Sol Pro',
    'openai/gpt-5.6-sol-pro:batch': 'OpenAI: GPT-5.6 Sol Pro (batch)',
    'openai/gpt-5.6-sol:batch': 'OpenAI: GPT-5.6 Sol (batch)',
    'openai/gpt-5.6-terra': 'OpenAI: GPT-5.6 Terra',
    'openai/gpt-5.6-terra-pro': 'OpenAI: GPT-5.6 Terra Pro',
    'openai/gpt-5.6-terra-pro:batch': 'OpenAI: GPT-5.6 Terra Pro (batch)',
    'openai/gpt-5.6-terra:batch': 'OpenAI: GPT-5.6 Terra (batch)',
    'openai/gpt-5:batch': 'OpenAI: GPT-5 (batch)',
    'openai/gpt-6-astra': 'OpenAI: GPT-6 Astra',
    'openai/gpt-6-astra-pro': 'OpenAI: GPT-6 Astra Pro',
    'openai/gpt-6-astra-pro:batch': 'OpenAI: GPT-6 Astra Pro (batch)',
    'openai/gpt-6-astra:batch': 'OpenAI: GPT-6 Astra (batch)',
    'openai/gpt-6-luna': 'OpenAI: GPT-6 Luna',
    'openai/gpt-6-luna-pro': 'OpenAI: GPT-6 Luna Pro',
    'openai/gpt-6-luna-pro:batch': 'OpenAI: GPT-6 Luna Pro (batch)',
    'openai/gpt-6-luna:batch': 'OpenAI: GPT-6 Luna (batch)',
    'openai/gpt-6-sol': 'OpenAI: GPT-6 Sol',
    'openai/gpt-6-sol-pro': 'OpenAI: GPT-6 Sol Pro',
    'openai/gpt-6-sol-pro:batch': 'OpenAI: GPT-6 Sol Pro (batch)',
    'openai/gpt-6-sol:batch': 'OpenAI: GPT-6 Sol (batch)',
    'openai/gpt-6.1-sol': 'OpenAI: GPT-6.1 Sol',
    'openai/gpt-6.1-sol-pro': 'OpenAI: GPT-6.1 Sol Pro',
    'openai/gpt-audio': 'OpenAI: GPT Audio',
    'openai/gpt-audio-mini': 'OpenAI: GPT Audio Mini',
    'openai/gpt-chat-latest': 'OpenAI: GPT Chat Latest',
    'openai/gpt-oss-120b': 'OpenAI: gpt-oss-120b',
    'openai/gpt-oss-120b:batch': 'OpenAI: gpt-oss-120b (batch)',
    'openai/gpt-oss-20b': 'OpenAI: gpt-oss-20b',
    'openai/gpt-oss-20b:batch': 'OpenAI: gpt-oss-20b (batch)',
    'openai/gpt-oss-safeguard-20b': 'OpenAI: gpt-oss-safeguard-20b',
    'openai/o1': 'OpenAI: o1',
    'openai/o3': 'OpenAI: o3',
    'openai/o3-mini': 'OpenAI: o3 Mini',
    'openai/o3-mini-high': 'OpenAI: o3 Mini High',
    'openai/o3-mini:batch': 'OpenAI: o3 Mini (batch)',
    'openai/o3-pro': 'OpenAI: o3 Pro',
    'openai/o3:batch': 'OpenAI: o3 (batch)',
    'openai/o4-mini': 'OpenAI: o4 Mini',
    'openai/o4-mini-high': 'OpenAI: o4 Mini High',
    'openai/o4-mini:batch': 'OpenAI: o4 Mini (batch)',
    'openrouter/auto': 'Auto Router',
    'openrouter/auto-beta': 'Auto Router (Beta)',
    'openrouter/free': 'Free Models Router',
    'openrouter/fusion': 'OpenRouter: Fusion',
    'perceptron/perceptron-mk1.5': 'Perceptron: Perceptron Mk1.5',
    'poolside/laguna-s-2.1': 'Poolside: Laguna S 2.1',
    'poolside/laguna-s-2.1:free': 'Poolside: Laguna S 2.1 (free)',
    'poolside/laguna-xs-2.1': 'Poolside: Laguna XS 2.1',
    'poolside/laguna-xs-2.1:free': 'Poolside: Laguna XS 2.1 (free)',
    'prism-ml/ternary-bonsai-2-27b': 'PrismML: Ternary Bonsai 2 27B',
    'qwen/qwen-2.5-72b-instruct': 'Qwen2.5 72B Instruct',
    'qwen/qwen-2.5-7b-instruct': 'Qwen: Qwen2.5 7B Instruct',
    'qwen/qwen-plus': 'Qwen: Qwen-Plus',
    'qwen/qwen-plus-2025-07-28': 'Qwen: Qwen Plus 0728',
    'qwen/qwen3-14b': 'Qwen: Qwen3 14B',
    'qwen/qwen3-235b-a22b': 'Qwen: Qwen3 235B A22B',
    'qwen/qwen3-235b-a22b-2507': 'Qwen: Qwen3 235B A22B Instruct 2507',
    'qwen/qwen3-235b-a22b-thinking-2507': 'Qwen: Qwen3 235B A22B Thinking 2507',
    'qwen/qwen3-30b-a3b': 'Qwen: Qwen3 30B A3B',
    'qwen/qwen3-30b-a3b-instruct-2507': 'Qwen: Qwen3 30B A3B Instruct 2507',
    'qwen/qwen3-30b-a3b-thinking-2507': 'Qwen: Qwen3 30B A3B Thinking 2507',
    'qwen/qwen3-32b': 'Qwen: Qwen3 32B',
    'qwen/qwen3-8b': 'Qwen: Qwen3 8B',
    'qwen/qwen3-coder': 'Qwen: Qwen3 Coder 480B A35B',
    'qwen/qwen3-coder-30b-a3b-instruct': 'Qwen: Qwen3 Coder 30B A3B Instruct',
    'qwen/qwen3-coder-flash': 'Qwen: Qwen3 Coder Flash',
    'qwen/qwen3-coder-next': 'Qwen: Qwen3 Coder Next',
    'qwen/qwen3-coder-plus': 'Qwen: Qwen3 Coder Plus',
    'qwen/qwen3-max': 'Qwen: Qwen3 Max',
    'qwen/qwen3-max-thinking': 'Qwen: Qwen3 Max Thinking',
    'qwen/qwen3-next-80b-a3b-instruct': 'Qwen: Qwen3 Next 80B A3B Instruct',
    'qwen/qwen3-next-80b-a3b-thinking': 'Qwen: Qwen3 Next 80B A3B Thinking',
    'qwen/qwen3-vl-235b-a22b-instruct': 'Qwen: Qwen3 VL 235B A22B Instruct',
    'qwen/qwen3-vl-235b-a22b-thinking': 'Qwen: Qwen3 VL 235B A22B Thinking',
    'qwen/qwen3-vl-30b-a3b-instruct': 'Qwen: Qwen3 VL 30B A3B Instruct',
    'qwen/qwen3-vl-30b-a3b-thinking': 'Qwen: Qwen3 VL 30B A3B Thinking',
    'qwen/qwen3-vl-32b-instruct': 'Qwen: Qwen3 VL 32B Instruct',
    'qwen/qwen3-vl-8b-instruct': 'Qwen: Qwen3 VL 8B Instruct',
    'qwen/qwen3-vl-8b-thinking': 'Qwen: Qwen3 VL 8B Thinking',
    'qwen/qwen3.5-122b-a10b': 'Qwen: Qwen3.5-122B-A10B',
    'qwen/qwen3.5-27b': 'Qwen: Qwen3.5-27B',
    'qwen/qwen3.5-35b-a3b': 'Qwen: Qwen3.5-35B-A3B',
    'qwen/qwen3.5-397b-a17b': 'Qwen: Qwen3.5 397B A17B',
    'qwen/qwen3.5-9b': 'Qwen: Qwen3.5-9B',
    'qwen/qwen3.5-flash-02-23': 'Qwen: Qwen3.5-Flash',
    'qwen/qwen3.5-plus-02-15': 'Qwen: Qwen3.5 Plus 2026-02-15',
    'qwen/qwen3.5-plus-20260420': 'Qwen: Qwen3.5 Plus 2026-04-20',
    'qwen/qwen3.6-27b': 'Qwen: Qwen3.6 27B',
    'qwen/qwen3.6-35b-a3b': 'Qwen: Qwen3.6 35B A3B',
    'qwen/qwen3.6-flash': 'Qwen: Qwen3.6 Flash',
    'qwen/qwen3.6-max-preview': 'Qwen: Qwen3.6 Max Preview',
    'qwen/qwen3.6-plus': 'Qwen: Qwen3.6 Plus',
    'qwen/qwen3.7-flash': 'Qwen: Qwen3.7 Flash',
    'qwen/qwen3.7-max': 'Qwen: Qwen3.7 Max',
    'qwen/qwen3.7-plus': 'Qwen: Qwen3.7 Plus',
    'qwen/qwen3.8-2.4t-a95b': 'Qwen: Qwen3.8 2.4T A95B',
    'qwen/qwen3.8-27b': 'Qwen: Qwen3.8 27B',
    'qwen/qwen3.8-27b:free': 'Qwen: Qwen3.8 27B (free)',
    'qwen/qwen3.8-flash': 'Qwen: Qwen3.8 Flash',
    'qwen/qwen3.8-max-0902': 'Qwen: Qwen3.8 Max (0902)',
    'qwen/qwen3.8-max-prime': 'Qwen: Qwen3.8 Max Prime',
    'qwen/qwen3.8-omni-flash': 'Qwen: Qwen3.8 Omni Flash',
    'rekaai/reka-edge': 'Reka Edge',
    'relace/relace-search': 'Relace: Relace Search',
    'sakana/fugu-max': 'Sakana: Fugu Max',
    'sakana/fugu-ultra': 'Sakana: Fugu Ultra',
    'sakana/fugu-ultra-v2': 'Sakana: Fugu Ultra v2',
    'sakana/sakana-namazu': 'Sakana: Sakana Namazu',
    'sao10k/l3.1-euryale-70b': 'Sao10K: Llama 3.1 Euryale 70B v2.2',
    'stealth/space-bunny-alpha': 'Space Bunny Alpha',
    'stepfun/step-3.5-flash': 'StepFun: Step 3.5 Flash',
    'stepfun/step-3.7-flash': 'StepFun: Step 3.7 Flash',
    'tencent/hy3': 'Tencent: Hy3',
    'tencent/hy3-preview': 'Tencent: Hy3 preview',
    'tencent/hy4-preview': 'Tencent: Hy4 preview',
    'thinkingmachines/inkling': 'Thinking Machines: Inkling',
    'thinkingmachines/inkling-small': 'Thinking Machines: Inkling Small',
    'thinkingmachines/inkling-small:free':
        'Thinking Machines: Inkling Small (free)',
    'thinkingmachines/inkling:free': 'Thinking Machines: Inkling (free)',
    'typesafe/jev-router': 'TypeSafe: Jev Router',
    'unbiased/pareto': 'Pareto',
    'unbiased/pareto-26.10-preview': 'Pareto 26.10 Preview',
    'upstage/solar-mini4': 'Upstage: Solar Mini 4',
    'upstage/solar-pro-3': 'Upstage: Solar Pro 3',
    'upstage/solar-pro4': 'Upstage: Solar Pro 4',
    'x-ai/grok-4.20': 'SpaceXAI: Grok 4.20',
    'x-ai/grok-4.3': 'SpaceXAI: Grok 4.3',
    'x-ai/grok-4.3:batch': 'SpaceXAI: Grok 4.3 (batch)',
    'x-ai/grok-4.5': 'SpaceXAI: Grok 4.5',
    'x-ai/grok-4.6': 'SpaceXAI: Grok 4.6',
    'x-ai/grok-4.7': 'SpaceXAI: Grok 4.7',
    'x-ai/grok-build-0.1': 'SpaceXAI: Grok Build 0.1',
    'xiaomi/mimo-v2.5': 'Xiaomi: MiMo-V2.5',
    'xiaomi/mimo-v2.5-pro': 'Xiaomi: MiMo-V2.5-Pro',
    'xiaomi/mimo-v2.6-flash': 'Xiaomi: MiMo-V2.6-Flash',
    'xiaomi/mimo-v2.6-pro': 'Xiaomi: MiMo-V2.6-Pro',
    'xiaomi/mimo-v2.6-pro-ultraspeed': 'Xiaomi: MiMo-V2.6-Pro-UltraSpeed',
    'z-ai/glm-4.5': 'Z.ai: GLM 4.5',
    'z-ai/glm-4.5-air': 'Z.ai: GLM 4.5 Air',
    'z-ai/glm-4.5v': 'Z.ai: GLM 4.5V',
    'z-ai/glm-4.6': 'Z.ai: GLM 4.6',
    'z-ai/glm-4.6v': 'Z.ai: GLM 4.6V',
    'z-ai/glm-4.7': 'Z.ai: GLM 4.7',
    'z-ai/glm-4.7-flash': 'Z.ai: GLM 4.7 Flash',
    'z-ai/glm-5': 'Z.ai: GLM 5',
    'z-ai/glm-5-turbo': 'Z.ai: GLM 5 Turbo',
    'z-ai/glm-5.1': 'Z.ai: GLM 5.1',
    'z-ai/glm-5.2': 'Z.ai: GLM 5.2',
    'z-ai/glm-5.3': 'Z.ai: GLM 5.3',
    'z-ai/glm-5.3-flash': 'Z.ai: GLM 5.3 Flash',
    'z-ai/glm-5.3-flash:batch': 'Z.ai: GLM 5.3 Flash (batch)',
    'z-ai/glm-5.3-flashx': 'Z.ai: GLM 5.3 FlashX',
    'z-ai/glm-5.3-prime': 'Z.ai: GLM 5.3 Prime',
    'z-ai/glm-5.3:batch': 'Z.ai: GLM 5.3 (batch)',
    'z-ai/glm-5v-turbo': 'Z.ai: GLM 5V Turbo',
    '~anthropic/claude-fable-latest': 'Anthropic: Claude Fable Latest',
    '~anthropic/claude-haiku-latest': 'Anthropic: Claude Haiku Latest',
    '~anthropic/claude-opus-latest': 'Anthropic: Claude Opus Latest',
    '~anthropic/claude-sonnet-latest': 'Anthropic: Claude Sonnet Latest',
    '~deepseek/deepseek-flash-latest': 'DeepSeek: DeepSeek Flash Latest',
    '~deepseek/deepseek-pro-latest': 'DeepSeek: DeepSeek Pro Latest',
    '~deepseek/deepseek-v4-flash-latest': 'DeepSeek: DeepSeek V4 Flash Latest',
    '~google/gemini-flash-latest': 'Google: Gemini Flash Latest',
    '~google/gemini-pro-latest': 'Google: Gemini Pro Latest',
    '~moonshotai/kimi-latest': 'MoonshotAI: Kimi Latest',
    '~openai/gpt-astra-latest': 'OpenAI: GPT Astra Latest',
    '~openai/gpt-luna-latest': 'OpenAI: GPT Luna Latest',
    '~openai/gpt-mini-latest': 'OpenAI: GPT Mini Latest',
    '~openai/gpt-sol-latest': 'OpenAI: GPT Sol Latest',
    '~openai/gpt-terra-latest': 'OpenAI: GPT Terra Latest',
    '~x-ai/grok-latest': 'xAI: Grok Latest',
    '~z-ai/glm-flash-latest': 'Z.ai: GLM Flash Latest',
    '~z-ai/glm-latest': 'Z.ai: GLM Latest',
  },
  'xai': {
    'grok-4.3': 'Grok 4.3',
    'grok-4.5': 'Grok 4.5',
    'grok-4.6': 'Grok 4.6',
    'grok-4.7': 'Grok 4.7',
  },
  'mistral': {
    'codestral-latest': 'Codestral (latest)',
    'devstral-2512': 'Devstral 2',
    'devstral-latest': 'Devstral 2',
    'devstral-medium-2507': 'Devstral Medium',
    'devstral-medium-latest': 'Devstral 2 (latest)',
    'devstral-small-2505': 'Devstral Small 2505',
    'devstral-small-2507': 'Devstral Small',
    'labs-devstral-small-2512': 'Devstral Small 2',
    'magistral-medium-latest': 'Magistral Medium (latest)',
    'ministral-3b-latest': 'Ministral 3B (latest)',
    'ministral-8b-latest': 'Ministral 8B (latest)',
    'mistral-large-2411': 'Mistral Large 2.1',
    'mistral-large-2512': 'Mistral Large 3',
    'mistral-large-latest': 'Mistral Large (latest)',
    'mistral-medium-2505': 'Mistral Medium 3',
    'mistral-medium-2508': 'Mistral Medium 3.1',
    'mistral-medium-2604': 'Mistral Medium 3.5',
    'mistral-medium-3.5': 'Mistral Medium 3.5',
    'mistral-medium-latest': 'Mistral Medium (latest)',
    'mistral-nemo': 'Mistral Nemo',
    'mistral-small-2506': 'Mistral Small 3.2',
    'mistral-small-2603': 'Mistral Small 4',
    'mistral-small-latest': 'Mistral Small (latest)',
    'open-mistral-7b': 'Mistral 7B',
    'open-mistral-nemo': 'Open Mistral Nemo',
    'open-mixtral-8x22b': 'Mixtral 8x22B',
    'open-mixtral-8x7b': 'Mixtral 8x7B',
    'pixtral-12b': 'Pixtral 12B',
    'pixtral-large-latest': 'Pixtral Large (latest)',
    'voxtral-small-latest': 'Voxtral Small (latest)',
    'zai-glm-5-2': 'GLM-5.2',
    'zai-glm-5-3': 'GLM-5.3',
  },
  'groq': {
    'llama-3.1-8b-instant': 'Llama 3.1 8B',
    'llama-3.3-70b-versatile': 'Llama 3.3 70B',
    'openai/gpt-oss-120b': 'GPT OSS 120B',
    'openai/gpt-oss-20b': 'GPT OSS 20B',
    'openai/gpt-oss-safeguard-20b': 'Safety GPT OSS 20B',
    'qwen/qwen3.6-27b': 'Qwen3.6 27B',
    'qwen/qwen3.8-27b': 'Qwen3.8 27B',
  },
  'cerebras': {'gpt-oss-120b': 'GPT OSS 120B', 'qwen-3.8-27b': 'Qwen3.8 27B'},
  'minimax': {
    'MiniMax-M2.7': 'MiniMax-M2.7',
    'MiniMax-M2.7-highspeed': 'MiniMax-M2.7-highspeed',
    'MiniMax-M3': 'MiniMax-M3',
  },
  'minimax-cn': {
    'MiniMax-M2.7': 'MiniMax-M2.7',
    'MiniMax-M2.7-highspeed': 'MiniMax-M2.7-highspeed',
    'MiniMax-M3': 'MiniMax-M3',
  },
  'kimi-coding': {
    'k3': 'Kimi K3',
    'k3-256k': 'Kimi K3-256K',
    'kimi-for-coding': 'kimi-for-coding',
    'kimi-for-coding-highspeed': 'Kimi For Coding HighSpeed',
  },
  'moonshotai': {
    'kimi-k2.6': 'Kimi K2.6',
    'kimi-k2.7-code': 'Kimi K2.7 Code',
    'kimi-k2.7-code-highspeed': 'Kimi K2.7 Code HighSpeed',
    'kimi-k3': 'Kimi K3',
  },
  'moonshotai-cn': {
    'kimi-k2.6': 'Kimi K2.6',
    'kimi-k2.7-code': 'Kimi K2.7 Code',
    'kimi-k2.7-code-highspeed': 'Kimi K2.7 Code HighSpeed',
    'kimi-k3': 'Kimi K3',
  },
  'qwen-token-plan': {
    'MiniMax-M2.5': 'MiniMax-M2.5',
    'deepseek-v3.2': 'DeepSeek V3.2',
    'deepseek-v4-flash': 'DeepSeek V4 Flash',
    'deepseek-v4-flash-0731': 'DeepSeek V4 Flash 0731',
    'deepseek-v4-pro': 'DeepSeek V4 Pro',
    'deepseek-v4-pro-0813': 'DeepSeek V4 Pro 0813',
    'deepseek-v4.1-flash': 'DeepSeek V4.1 Flash',
    'glm-5': 'GLM-5',
    'glm-5.1': 'GLM-5.1',
    'glm-5.2': 'GLM-5.2',
    'glm-5.3': 'GLM-5.3',
    'kimi-k2.5': 'Kimi K2.5',
    'kimi-k2.6': 'Kimi K2.6',
    'kimi-k2.7-code': 'Kimi K2.7 Code',
    'qwen3.6-flash': 'Qwen3.6 Flash',
    'qwen3.6-plus': 'Qwen3.6 Plus',
    'qwen3.7-max': 'Qwen3.7 Max',
    'qwen3.7-plus': 'Qwen3.7 Plus',
    'qwen3.8-flash': 'Qwen3.8 Flash',
    'qwen3.8-max': 'Qwen3.8 Max',
  },
  'qwen-token-plan-cn': {
    'MiniMax-M2.5': 'MiniMax-M2.5',
    'deepseek-v3.2': 'DeepSeek V3.2',
    'deepseek-v4-flash': 'DeepSeek V4 Flash',
    'deepseek-v4-flash-0731': 'DeepSeek V4 Flash 0731',
    'deepseek-v4-pro': 'DeepSeek V4 Pro',
    'deepseek-v4-pro-0813': 'DeepSeek V4 Pro 0813',
    'deepseek-v4.1-flash': 'DeepSeek V4.1 Flash',
    'glm-5': 'GLM-5',
    'glm-5.1': 'GLM-5.1',
    'glm-5.2': 'GLM-5.2',
    'glm-5.3': 'GLM-5.3',
    'kimi-k2.5': 'Kimi K2.5',
    'kimi-k2.6': 'Kimi K2.6',
    'kimi-k2.7-code': 'Kimi K2.7 Code',
    'qwen3.6-flash': 'Qwen3.6 Flash',
    'qwen3.6-plus': 'Qwen3.6 Plus',
    'qwen3.7-max': 'Qwen3.7 Max',
    'qwen3.7-plus': 'Qwen3.7 Plus',
    'qwen3.8-flash': 'Qwen3.8 Flash',
    'qwen3.8-max': 'Qwen3.8 Max',
  },
  'qwen-token-plan-individual': {
    'deepseek-v4-flash-0731': 'DeepSeek V4 Flash 0731',
    'deepseek-v4-pro': 'DeepSeek V4 Pro',
    'deepseek-v4-pro-0813': 'DeepSeek V4 Pro 0813',
    'glm-5.2': 'GLM-5.2',
    'qwen3.6-flash': 'Qwen3.6 Flash',
    'qwen3.7-max': 'Qwen3.7 Max',
    'qwen3.7-plus': 'Qwen3.7 Plus',
    'qwen3.8-flash': 'Qwen3.8 Flash',
    'qwen3.8-max': 'Qwen3.8 Max',
  },
};
